name: Caller

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  test:
    name: Test
    uses: Serneum/gh-actions-test/.github/workflows/called-workflow.yml@main
    secrets: inherit
